### PR TITLE
Allow using a custom Cursor implementation

### PR DESCRIPTION
**Pull request by jeroenvisser101**
This PR builds on top of #2, since it includes similar code style changes.

This adds a `CursorTranslator` behaviour. The `Base64Hashed` Cursor implements this behaviour, but users of this library can pass their own module as long as it implements the `CursorTranslator` behaviour.

This also alters the default cursor implementation to check the checksum. This makes it "A tamper-resistant (not tamper-proof) implementation that uses base64 and a hashed padding.". This should not (but can be considered to) be a breaking change.

### CODE REVIEW

**Comment by nathanl** [comment]
Thanks for breaking this into a separate PR. It made it easier for me to understand.

This is awesome work! 💯 The checksum check is very nice. 👍

**Comment by jeroenvisser101** [comment]
Thanks for taking the time to review and for open-sourcing this library!

**Comment by nathanl** [comment]
@jeroenvisser101 With your changes merged, I went ahead and published this package. https://hex.pm/packages/absinthe_relay_keyset_connection

**Comment by jeroenvisser101** [comment]
Oh that's awesome! Thanks again!

**Pull request merged**
